<?php
if (!function_exists('rb_get_notice_text')) :
    function rb_get_notice_text()
    {
        $text = __('This is the notice text', 'rb');

        return apply_filter('rb_notice_text', $text);
    }
endif;

/**
 * I think filter is the best way to do it, because this function may be used in many places,
 * so if we are using a filter, we can apply some additional conditions like checking current_screen(), etc.
 * By doing this, we are not only changing text, but also saving the html that will be generated by a parent theme,
 * which may be changed with a parent theme update to a newer version.
 * It's also possible to rewrite a function, since WordPress will take a child-theme function implementation,
 * but I prefer to use a filter for the reason mentioned above.
 */

add_filter('rb_notice_text', function ($text) {
    return 'This is an updated message';
});
?>